version: 0.0
os: linux
files:
  - source: app/
    destination: /etc/deploy/app
  - source: Dockerfile 
    destination: /etc/deploy/
  - source: docker-compose.yml
    destination: /etc/deploy/ 
hooks:
  BeforeInstall:
    - location: scripts/beforeBuild.sh
      timeout: 180
  AfterInstall:
    - location: scripts/servicesTest.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/buildImage.sh
      timeout: 1800
      runas: root
  ValidateService:
    - location: scripts/validApp.sh
      timeout: 1800
